#!/bin/bash

########################
# include the magic
########################
. demo-magic.sh

# hide the evidence
clear

pe "./k8sgpt analyze --explain"

pe "./k8sgpt filter list"

pe "./k8sgpt integration list"

pe "./k8sgpt integration activate trivy"

pe "./k8sgpt analyze --filter VulnerabilityReport -o json | jq ."
